{{- if .Values.jira.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "chart.fullname" . ) "jira" }}
type: Opaque
data:
{{- with .Values.jira }}
  url: {{ .url | b64enc }}
  token: {{ .token | b64enc  }}
{{- if .ssl }}
{{- if .ssl.ca }}
  ca.pem: {{ .ssl.ca | b64enc }}
{{- end }}
{{- if .ssl.cert }}
  cert.pem: {{ .ssl.cert | b64enc }}
{{- end }}
{{- if .ssl.key }}
  key.pem: {{ .ssl.key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}