global:
  ## Set Argon Server Address and token. Manadatory values
  argonServer: https://app-broker.argon.io
  token: 

  ### Set Registry to pull images (default - docker.io)
  # registry: "docker.io"
  
  ### Optionally Set Global Envs, for example for proxy
  # env: 
  #   HTTP_PROXY: proxy.example.com:3128
  #   HTTPS_PROXY: proxy.example.com:3128

  ### Optionally set common pod labels
  # commonPodLabels: {}

#######################################################
#  Bitbucket 
#######################################################
bitbucket:
  url: 
  username: bitbucket
  password:
  ### Optionally add ssl ca cert and client cert/key for ssl connection to the server 
  # ssl:
  #   ca: -|
  #     -----BEGIN CERTIFICATE-----
  #     ca-cert
  #     -----END CERTIFICATE
  #   cert: -|
  #     -----BEGIN CERTIFICATE-----
  #     client-cert
  #     -----END CERTIFICATE-----
  #   key: -|
  #     -----BEGIN RSA PRIVATE KEY-----
  #     secure key
  #     -----BEGIN RSA PRIVATE KEY-----

  bitbucketBroker:
    nameSuffix: bitbucket-broker
    image:
      repository: argonsecurity/broker
      tag: bitbucket

    port: 9091
    service:
      type: ClusterIP
      annotations: {}
      
    resources: {}
    nodeSelector: {}
    affinity: {}
    tollerations: {}

  bitbucketSecretsScanner:
    nameSuffix: bitbucket-secrets-scanner
    image:
      repository: argonsecurity/secrets-scanner-broker
      tag: bitbucket

    port: 9094
    service:
      type: ClusterIP
      annotations: {}
      
    resources: {}
    nodeSelector: {}
    affinity: {}
    tollerations: {}

  bitbucketSastScanner:
    nameSuffix: bitbucket-sast-scanner
    image:
      repository: argonsecurity/sast-scanner-broker
      tag: bitbucket

    port: 9095
    service:
      type: ClusterIP
      annotations: {}
      
    resources: {}
    nodeSelector: {}
    affinity: {}
    tollerations: {}
    

#######################################################
#  Gitlab 
#######################################################
gitlab:
  url: 
  token: 
  ### Optionally add ssl ca cert and client cert/key for ssl connection to the server 
  # ssl:
  #   ca:
  #   cert:
  #   key:

  gitlabBroker:
    nameSuffix: gitlab-broker
    image:
      repository: argonsecurity/broker
      tag: gitlab

    port: 9091
    service:
      type: ClusterIP
      annotations: {}
      
    resources: {}
    nodeSelector: {}
    affinity: {}
    tollerations: {}

  gitlabSecretsScanner:
    nameSuffix: gitlab-secrets-scanner
    image:
      repository: argonsecurity/secrets-scanner-broker
      tag: gitlab

    port: 9094
    service:
      type: ClusterIP
      annotations: {}
      
    resources: {}
    nodeSelector: {}
    affinity: {}
    tollerations: {}

  gitlabSastScanner:
    nameSuffix: gitlab-sast-scanner
    image:
      repository: argonsecurity/sast-scanner-broker
      tag: gitlab

    port: 9095
    service:
      type: ClusterIP
      annotations: {}
      
    resources: {}
    nodeSelector: {}
    affinity: {}
    tollerations: {}
