{{- if .Values.bitbucket }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "chart.fullname" . ) "bitbucket" }}
type: Opaque
data:
  url: {{ .Values.bitbucket.url | b64enc }}
  username: {{ .Values.bitbucket.username | b64enc  }}
  password: {{ .Values.bitbucket.password | b64enc  }}
{{- if .Values.bitbucket.ssl }}
{{- if .Values.bitbucket.ssl.ca }}
  ca.pem: |- 
{{ .Files.Get .Values.bitbucket.ssl.ca | b64enc | indent 4 }}
{{- end }}
{{- if .Values.bitbucket.ssl.cert }}
  cert.pem: |- 
{{ .Files.Get .Values.bitbucket.ssl.cert | b64enc | indent 4 }}
{{- end }}
{{- if .Values.bitbucket.ssl.key }}
  key.pem: |- 
{{ .Files.Get .Values.bitbucket.ssl.key | b64enc | indent 4 }}
{{- end }}
{{- end }}
{{- end }}