{{- if .Values.bitbucket.url }}
{{- $v := .Values.bitbucket.bitbucketSastScanner }}
{{- $name := printf "%s-%s" (include "chart.fullname" . ) $v.nameSuffix }}
{{- $bitbucket_secret := printf "%s-%s" (include "chart.fullname" . ) "bitbucket" }}
{{- $ssl := dict "secret" $bitbucket_secret "ssl" .Values.bitbucket.ssl }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/bitbucket/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "common.podLabels" . | indent 8 }}      
    spec:
      containers:
        - name: {{ $name }}
          image: {{ include "common.image" (dict "image" $v.image "global" .Values.global) }}
          imagePullPolicy: {{ $v.image.pullPolicy | default "Always" }}
          env:
          - name: ARGON_SERVER
            value: {{ .Values.global.argonServer }}
          - name: TOKEN
            value: {{ .Values.global.token }}
          - name: PORT
            value: {{ $v.port  | quote }}
          - name: BASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ $bitbucket_secret }}
                key: url
          - name: BITBUCKET_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $bitbucket_secret }}
                key: username
          - name: BITBUCKET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $bitbucket_secret }}
                key: password
          {{- include "ssl.envs" $ssl | indent 10 }}
          {{- range $key, $value := $v.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $v.port }}
              protocol: TCP
          resources:
{{ toYaml $v.resources | indent 12 }}
          volumeMounts:
          {{- include "ssl.volumeMount" $ssl | indent 10 }}
      volumes:
      {{- include "ssl.volumeSecret" $ssl | indent 6 }}
    {{- with $v.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $v.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $v.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}