{{- if .Values.bitbucket.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "chart.fullname" . ) "bitbucket" }}
type: Opaque
data:
{{- with .Values.bitbucket }}
  url: {{ .url | b64enc }}
  username: {{ .username | b64enc  }}
  password: {{ .password | b64enc  }}
{{- if .ssl }}
{{- if .ssl.ca }}
  ca.pem: {{ .ssl.ca | b64enc }}
{{- end }}
{{- if .ssl.cert }}
  cert.pem: {{ .ssl.cert | b64enc }}
{{- end }}
{{- if .ssl.key }}
  key.pem: {{ .ssl.key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}