{{- if .Values.bitbucketSecretsScanner.enabled }}
{{- $v := .Values.bitbucketSecretsScanner }}
{{- $name := printf "%s-%s" (include "chart.fullname" . ) $v.nameSuffix }}
{{- $bitbucket_secret := printf "%s-%s" (include "chart.fullname" . ) "bitbucket" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "common.podLabels" . | indent 8 }}      
    spec:
      containers:
        - name: {{ $name }}
          image: {{ include "common.image" (dict "image" $v.image "global" .Values.global) }}
          imagePullPolicy: {{ $v.image.pullPolicy | default "Always" }}
          env:
          - name: ARGON_SERVER
            value: {{ .Values.global.argonServer }}
          - name: TOKEN
            value: {{ .Values.global.token }}
          - name: BASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ $bitbucket_secret }}
                key: url
          - name: BITBUCKET_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $bitbucket_secret }}
                key: username
          - name: BITBUCKET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $bitbucket_secret }}
                key: password
          {{- if .Values.bitbucket.ssl.ca }}
          - name: CA_CERT
            value: /etc/bitbucket-ssl/ca.pem
          {{- end }}
          {{- if .Values.bitbucket.ssl.cert }}
          - name: HTTPS_CERT
            value: /etc/bitbucket-ssl/cert.pem
          {{- end }}
          {{- if .Values.bitbucket.ssl.key }}
          - name: HTTPS_KEY
            value: /etc/bitbucket-ssl/key.pem
          {{- end }}
          {{- range $key, $value := $v.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}      
          {{- range $key, $value := $v.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $v.port }}
              protocol: TCP
          resources:
{{ toYaml $v.resources | indent 12 }}
      {{- if .Values.bitbucket.ssl }}
          volumeMounts:
          - name: bitbucket-ssl
            mountPath: "/etc/bitbucket-ssl"
      volumes:
      - name: bitbucket-ssl
        secret:
          secretName: {{ $bitbucket_secret }}
          items:
          {{- if .Values.bitbucket.ssl.ca }}
          - key: ca.pem
            path: ca.pem
          {{- end }}
          {{- if .Values.bitbucket.ssl.cert }}
          - key: cert.pem
            path: cert.pem
          {{- end }}
          {{- if .Values.bitbucket.ssl.key }}
          - key: key.pem
            path: key.pem
          {{- end }}
      {{- end }}
    {{- with $v.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $v.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $v.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}