{{- if .Values.azure.url }}
{{- $v := .Values.azure.azureBroker }}
{{- $name := printf "%s-%s" (include "chart.fullname" . ) $v.nameSuffix }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{ $v.service.annotations | toYaml | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ $v.service.port | default $v.port }}
    protocol: TCP
    targetPort: {{ $v.port }}
  type: {{ $v.service.type | default "ClusterIP" }}
{{- end }}